# fly.toml app configuration file generated for muscler-frontend on 2023-11-08T14:38:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muscler-frontend"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
